name: Sample CI

on:
  push:
    branches: [ test/gha ]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello from GitHub-hosted runner"

      - name: Show files
        run: ls -R